### ISSUE TITLE
IsList

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/primitive-containers#1]
Also, all of these types should be given IsList  instances.

**Comment by andrewthad** [comment]
There are two ways to write the `IsList` instance. One would be to naively fold over the elements, turning them into singleton sets and unioning them as you go. Alternatively, you could load them into a buffer in `O(n)` time, do an in-place stable sort like mergesort in `O(n log n)` time, and then do something like what the unix tool `uniq` does, removing adjacent duplicates of a sorted list in `O(n)` times. This would bring the total complexity down from `O(n^2)` down to `O(n log n)`. Also, you can do something similar with `mconcat`, avoiding the default definition in favor of something like this (it will be a little messier though since you want to take advantage of the fact that your working with sets that have already been sorted).

**Comment by andrewthad** [comment]
I've got a repo where I implemented a [concurrent variant of mergesort](https://github.com/andrewthad/mergesort/blob/master/src/Sort/Merge.hs) some time ago. You could dump the concurrency and switch to `PrimArray` instead of `ByteArray`, and this would work.

**Comment by chessai** [comment]
WE SHOULD KEEP THE CONCURRENCY. GOTTA GO FAST. CC @mckeankylej @taktoa

**Comment by mckeankylej** [comment]
What about `PrimArray`s make it so you cant use concurrency?

**Comment by chessai** [comment]
IsList seems done for everything except Diet-Sets/Maps now
