### ISSUE TITLE
Difference Operation on Diet Set

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/primitive-containers#5]
It would be useful in another project I'm working on to have access to a difference operator for diet sets (which I recently implemented). @chessai Feel free to give this a shot when you are available.

As a side note, the difference function should not need an `Enum` constraint. Also, it may be helpful to implement difference for ordinary sets first. It would use the same "fold over two arrays simultaneously" approach, but it would be more simple. It probably never will make sense to implement difference for diet maps (or ordinary maps for that matter) since it would require some notion of subtracting values and would require removing values that are, in some sense, a monoidal identity.

**Comment by chessai** [comment]
cancelling in maps makes sense (i think) in a cancellative group. seeing as no such typeclass is common, not even a group typeclass, it's probably nowhere near worth it

**Comment by chessai** [comment]
tomorrow if I have time I will implement this for ordinary sets and then diet sets

**Comment by andrewthad** [comment]
I spent some more time last night thinking about the idea of difference on maps. As an advance notice, I now feel even more strongly tha it's not worth doing. The main problem is that maps that support difference need an almost entirely different interface. To start, let's assume we have:

```
class Monoid a => Cancellative a where
  difference :: a -> a -> a
class Cancellative a => Invertible a where
  invert :: a -> a
```

With the following laws:

```
difference a a === mempty
invert (invert a) === a
difference a b === a <> invert b
```

So, types like `Ord a => Set a` are have an instance for `Cancellative` and types like `Num a => Sum a` have instances for both `Cancellative` and `Invertible`. (Also, this is pretty different from how `monoid-subclasses` defines a cancellative monoid. There may be a better name for what I am describing). Now, the whole interface to map ends up looking different. For instance, consider `<>`. To satisfy the implied law that `a <> invert a === mempty`, it must eliminate elements that are considered mempty. So, the `Semigroup` instance for `Map` incurs a stronger constraint (`Monoid`) on it's element type than it previously did (`Semigroup`). We end up with:

```
data Map k v
instance (Ord k, Monoid v) => Semigroup (Map k v)
instance (Ord k, Monoid v) => Monoid (Map k v)
instance (Ord k, Cancellative v) => Cancellative (Map k v)
instance (Ord k, Invertible v) => Invertible (Map k v)
```

And here's the kicker: Even `lookup` now has a better type signature for this settings:

    lookup :: (Ord k, Monoid v) => k -> Map k v -> v

Why? There's a "lookup law" that it's nice to have:

    lookup (singleton k x <> singleton k y) === x <> y

On ordinary maps, we have a variant of this where there's a `Just` wrapping the RHS. But in this setting, since two values at the same key might eliminate each other, it's easier to state this law when `lookup` provides `mempty` for missing elements.

**Comment by chessai** [comment]
```
class Semigroup a => Cancellative a where
  (</>) :: a -> a -> a

class (Monoid a, Cancellative a) => Invertible a where
  invert :: a -> a
```

I think this is correct, you don't need an identity to be cancellative

**Comment by chessai** [comment]
that lookup law should probably be included in the docs

**Comment by chessai** [comment]
we should write better docs. i will help with that when i have time. i have something i need to do for alan today, and then this if possible

**Comment by andrewthad** [comment]
The law I gave for `Cancellative` requires an identity element:

    difference a a === mempty

Without a `Monoid` superclass constraint, it would have no laws. Although you may have different laws in mind.

But yeah, the docs (especially for diet sets and diet maps, since no one knows what those are) could use improvement. Including examples would be good.

**Comment by chessai** [comment]
I think we mistook cancellative semigroups for rings -

```haskell
class Semiring a => Ring a where
  negate :: a -> a

difference :: Ring a => a -> a -> a
difference x y = x + (negate y)
```

Laws:

```haskell


negate (negate a) === a
difference a a === zero
difference a b === a + negate b

```

**Comment by chessai** [comment]
If we wanted to stick to monoids, we could do this:

```haskell
class Monoid a => Invertible a where
  invert :: a -> a

difference :: Invertible a => a -> a -> a
difference x y = x <> invert y
```

with the obvious (and aforementioned) laws.

I think this is my fault because I said cancellative, which is a totally different property than what is needed

**Comment by chessai** [comment]
cancellative semigroups are somewhat more annoying because they are not guaranteed to be fully cancellative - they can be left cancellative or right cancellative, or both. groups are nicer because they must be both. however what we would need for this is just a weaker form of a ring

**Comment by andrewthad** [comment]
The reason I had `Cancellative` (which maybe means something totally different that I thought it did, maybe subtractable is a better name) as a superclass of `Invertible` is that there are things that you can take the difference of that cannot be inverted. One example is sets. So, we get:

```
class Monoid a => Subtractable a where
    difference :: a -> a -> a
instance Ord a => Subtractable (Set a)
instance (Ord k, Subtractable v) => Subtractable (Map k v)
```

And now `difference` can specialize to things like:

    difference :: Map Int (Set PersonId) -> Map Int (Set PersonId) -> Map Int (Set PersonId)

With `Invertible`, we cannot support `Set` as a value of in the map.

**Comment by andrewthad** [comment]
Dang, we just posted at the same time.

**Comment by chessai** [comment]
what you want is cancellative then

**Comment by andrewthad** [comment]
Subtraction semigroups have the properties I false ascribed to cancellative semigroups. https://dml.cz/bitstream/handle/10338.dmlcz/126093/MathBohem_120-1995-4_10.pdf

**Comment by chessai** [comment]
that makes sense. i figured there was something like that but couldn't find it online

**Comment by andrewthad** [comment]
And I was wrong again. Subtraction semigroups are more like having a multiplication operator and a subtraction operator. The real solution is called Commutative Monoid with Monus. I've written a package called `monus` that plays around with this.

**Comment by andrewthad** [comment]
Original issue of diet set difference resolved by https://github.com/andrewthad/primitive-containers/pull/6
