### ISSUE TITLE
Add `empty` function without constraints

### ISSUE THREAD

**Issue by ChShersh** [andrewthad/primitive-containers#7]
Currently there's no way to create empty `Map` or `Set` for types that don't satisfy some constraints.

Currently I see the following ways to create empty `Map`:

1. `fromList []`: requires `Ord` constraint for keys.
2. `mempty`: requires `Ord` constraint for keys and `Semigroup` constraint for values.

Not having `empty` function without constraints makes it difficult to implement generalized interface for maps and sets:

* https://github.com/kowainik/containers-backpack/issues/25

**Comment by andrewthad** [comment]
This has been fixed in master for some time now, but I just got around to releasing it to hackage as `primitive-containers-0.3`. Let me know if there is anything else missing.

**Comment by ChShersh** [comment]
@andrewthad Thanks a lot!
